"""Report generation utilities."""

import json
from datetime import datetime
from pathlib import Path
from typing import Any, Dict, List

from jinja2 import Template


class ReportGenerator:
    """Generates penetration testing reports."""

    def __init__(self, output_dir: Path, format: str = "markdown"):
        """
        Initialize report generator.

        Args:
            output_dir: Directory to save reports
            format: Report format (markdown, html, json)
        """
        self.output_dir = output_dir
        self.format = format
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_report(self, session_id: str, data: Dict[str, Any]) -> Path:
        """
        Generate report from session data.

        Args:
            session_id: Session identifier
            data: Session data

        Returns:
            Path to generated report
        """
        if self.format == "markdown":
            return self._generate_markdown_report(session_id, data)
        elif self.format == "html":
            return self._generate_html_report(session_id, data)
        elif self.format == "json":
            return self._generate_json_report(session_id, data)
        else:
            raise ValueError(f"Unsupported format: {self.format}")

    def _generate_markdown_report(self, session_id: str, data: Dict[str, Any]) -> Path:
        """Generate Markdown report."""
        report_path = self.output_dir / f"report_{session_id}.md"

        # Extract data
        start_time = data.get("start_time", "N/A")
        end_time = data.get("end_time", "N/A")
        commands = data.get("commands", [])
        findings = data.get("findings", [])
        screenshots = data.get("screenshots", [])

        # Build report
        report = f"""# Lucifer Penetration Testing Report

**Session ID:** {session_id}  
**Start Time:** {start_time}  
**End Time:** {end_time}  
**Generated:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}

---

## Executive Summary

This report documents the findings from an automated penetration testing session conducted using Lucifer AI Assistant.

## Commands Executed

Total commands: {len(commands)}

"""

        for i, cmd in enumerate(commands, 1):
            report += f"""### {i}. Command
- **Timestamp:** {cmd.get('timestamp', 'N/A')}
- **Command:** `{cmd.get('command', 'N/A')}`

"""

        report += f"""## Findings

Total findings: {len(findings)}

"""

        for i, finding in enumerate(findings, 1):
            report += f"""### Finding {i}
- **Timestamp:** {finding.get('timestamp', 'N/A')}
- **Type:** {finding.get('type', 'N/A')}
- **Content:**
```
{finding.get('content', 'N/A')}
```

"""

        report += f"""## Screenshots

Total screenshots: {len(screenshots)}

"""

        for i, screenshot in enumerate(screenshots, 1):
            report += f"{i}. ![Screenshot {i}]({screenshot})\n"

        report += """
---

## Recommendations

1. Review all findings and verify vulnerabilities
2. Implement security patches and fixes
3. Conduct follow-up testing
4. Update security policies

## Disclaimer

This report is generated by an automated AI system and should be reviewed by qualified security professionals. Results may contain false positives and should be verified.

---

*Generated by Lucifer AI Assistant*
"""

        # Write report
        report_path.write_text(report)
        return report_path

    def _generate_html_report(self, session_id: str, data: Dict[str, Any]) -> Path:
        """Generate HTML report."""
        report_path = self.output_dir / f"report_{session_id}.html"

        html_template = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lucifer Pentest Report - {{ session_id }}</title>
    <style>
        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 1200px;
            margin: 0 auto;
            padding: 20px;
            background: #1e1e1e;
            color: #d4d4d4;
        }
        h1 { color: #4ec9b0; border-bottom: 2px solid #4ec9b0; padding-bottom: 10px; }
        h2 { color: #569cd6; margin-top: 30px; }
        .meta { background: #2d2d2d; padding: 15px; border-radius: 5px; margin: 20px 0; }
        .command { background: #1e1e1e; border-left: 3px solid #569cd6; padding: 10px; margin: 10px 0; }
        .finding { background: #2d2d2d; border-left: 3px solid #ce9178; padding: 15px; margin: 10px 0; }
        code { background: #1e1e1e; padding: 2px 6px; border-radius: 3px; color: #ce9178; }
        pre { background: #1e1e1e; padding: 15px; border-radius: 5px; overflow-x: auto; }
        .screenshot { max-width: 100%; margin: 10px 0; border: 1px solid #3e3e3e; }
    </style>
</head>
<body>
    <h1>🔥 Lucifer Penetration Testing Report</h1>
    
    <div class="meta">
        <strong>Session ID:</strong> {{ session_id }}<br>
        <strong>Start Time:</strong> {{ start_time }}<br>
        <strong>End Time:</strong> {{ end_time }}<br>
        <strong>Generated:</strong> {{ generated }}
    </div>

    <h2>📋 Commands Executed ({{ commands|length }})</h2>
    {% for cmd in commands %}
    <div class="command">
        <strong>{{ loop.index }}.</strong> <code>{{ cmd.command }}</code><br>
        <small>{{ cmd.timestamp }}</small>
    </div>
    {% endfor %}

    <h2>🎯 Findings ({{ findings|length }})</h2>
    {% for finding in findings %}
    <div class="finding">
        <strong>Finding {{ loop.index }}</strong><br>
        <strong>Type:</strong> {{ finding.type }}<br>
        <strong>Time:</strong> {{ finding.timestamp }}<br>
        <pre>{{ finding.content }}</pre>
    </div>
    {% endfor %}

    <h2>📸 Screenshots ({{ screenshots|length }})</h2>
    {% for screenshot in screenshots %}
    <img src="{{ screenshot }}" class="screenshot" alt="Screenshot {{ loop.index }}">
    {% endfor %}

    <h2>💡 Recommendations</h2>
    <ul>
        <li>Review all findings and verify vulnerabilities</li>
        <li>Implement security patches and fixes</li>
        <li>Conduct follow-up testing</li>
        <li>Update security policies</li>
    </ul>

    <hr>
    <p><em>Generated by Lucifer AI Assistant</em></p>
</body>
</html>
"""

        template = Template(html_template)
        html = template.render(
            session_id=session_id,
            start_time=data.get("start_time", "N/A"),
            end_time=data.get("end_time", "N/A"),
            generated=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
            commands=data.get("commands", []),
            findings=data.get("findings", []),
            screenshots=data.get("screenshots", []),
        )

        report_path.write_text(html)
        return report_path

    def _generate_json_report(self, session_id: str, data: Dict[str, Any]) -> Path:
        """Generate JSON report."""
        report_path = self.output_dir / f"report_{session_id}.json"

        report_data = {
            "session_id": session_id,
            "generated": datetime.now().isoformat(),
            "data": data,
        }

        report_path.write_text(json.dumps(report_data, indent=2))
        return report_path
